### Login
POST {{api_auth}}/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
    client.global.set("auth_token", response.body.data);
    const xTenantId = response.headers.valueOf("X-Tenant-Id");
    client.global.set("x_tenant_id", xTenantId);
%}

### create an event
POST {{api_event_events}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-Tenant-Id: {{x_tenant_id}}

{
  "name": "Smart",
  "description": "Smart",
  "code": "TEST2",
  "phone": "1234567890",
  "document": "TEST1234",
  "address": "S/D",
  "industry": "Comercio",
  "enable" : true
}

### Get event files
< {%
    request.variables.set("auth_token", client.global.get("auth_token"));
    console.log(client.global.get("auth_token"))
    request.variables.set("x_tenant_id", client.global.get("x_tenant_id"));
    console.log(client.global.get("x_tenant_id"))
%}
GET {{api_event_events}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-Tenant-Id: {{x_tenant_id}}

### Get roles by event
< {%
    request.variables.set("auth_token", client.global.get("auth_token"));
    console.log(client.global.get("auth_token"))
    request.variables.set("x_tenant_id", client.global.get("x_tenant_id"));
    console.log(client.global.get("x_tenant_id"))
%}
GET http://localhost:9001/api/v1/core/events/b4c8384a-c7eb-45d9-99e7-47b46244fcd8/roles
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-Tenant-Id: {{x_tenant_id}}


### Toogle Merchat Enable
< {%
    request.variables.set("auth_token", client.global.get("auth_token"));
    console.log(client.global.get("auth_token"))
    request.variables.set("x_tenant_id", client.global.get("x_tenant_id"));
    console.log(client.global.get("x_tenant_id"))
%}
PUT http://localhost:9001/api/v1/core/events/2e9847a2-0b39-4e21-a545-fb730a0667c8/enable
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-Tenant-Id: {{x_tenant_id}}

{
  "enable": true
}

### Toogle Merchat Enable
< {%
    request.variables.set("auth_token", client.global.get("auth_token"));
    console.log(client.global.get("auth_token"))
    request.variables.set("x_tenant_id", client.global.get("x_tenant_id"));
    console.log(client.global.get("x_tenant_id"))
%}
PUT {{api_event_events}}/c2c98b56-5a0a-45a1-96b1-c4dc202edeeb
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-Tenant-Id: {{x_tenant_id}}

{
  "name": "Smart",
  "description": "Smart",
  "code": "TEST4",
  "phone": "1234567890",
  "document": "TEST4",
  "address": "S/D",
  "industry": "Comercio",
  "enable" : true
}

### Get Events summary
< {%
    request.variables.set("auth_token", client.global.get("auth_token"));
    console.log(client.global.get("auth_token"))
    request.variables.set("x_tenant_id", client.global.get("x_tenant_id"));
    console.log(client.global.get("x_tenant_id"))
%}
GET {{api_event_events}}/summary
Content-Type: application/json
Authorization: Bearer {{auth_token}}
X-Tenant-Id: {{x_tenant_id}}
#Merchant-Api-Key: 84cb99b7-ca31-45a4-af7a-75f815192033
#Store-Api-Key: 211231dd-2e52-4598-9720-7396a29f9229
