// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplateworkshopSpeakers = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/event/workshop-speakers": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get workshop speakers",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["WorkshopSpeakers"],
                "summary": "Get workshop speakers",
                "parameters": [
                    {"type": "integer", "description": "Page", "name": "page", "in": "query"},
                    {"type": "integer", "description": "Size page", "name": "size_page", "in": "query"},
                    {"type": "string", "description": "Filter by workshop id", "name": "workshop_id", "in": "query"},
                    {"type": "string", "description": "Filter by speaker id", "name": "speaker_id", "in": "query"}
                ],
                "responses": {
                    "200": {"description": "Success Request", "schema": {"$ref": "#/definitions/rest.workshopSpeakersResult"}},
                    "500": {"description": "Bad Request", "schema": {"$ref": "#/definitions/errorDomain.SmartError"}}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Create workshop speaker",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["WorkshopSpeakers"],
                "summary": "Create workshop speaker",
                "parameters": [
                    {"description": "Create workshop speaker body", "name": "createWorkshopSpeakerBody", "in": "body", "required": true, "schema": {"$ref": "#/definitions/rest.createWorkshopSpeakerValidated"}}
                ],
                "responses": {
                    "201": {"description": "Success Request", "schema": {"$ref": "#/definitions/httpResponse.IdResult"}},
                    "500": {"description": "Bad Request", "schema": {"$ref": "#/definitions/errorDomain.SmartError"}}
                }
            }
        },
        "/api/v1/event/workshop-speakers/{workshopSpeakerId}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get workshop speaker by id",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["WorkshopSpeakers"],
                "summary": "Get workshop speaker by id",
                "parameters": [
                    {"type": "string", "description": "the id of the workshop speaker", "name": "workshopSpeakerId", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "Success Request", "schema": {"$ref": "#/definitions/rest.workshopSpeakerByIdResult"}},
                    "500": {"description": "Bad Request", "schema": {"$ref": "#/definitions/errorDomain.SmartError"}}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "description": "Delete workshop speaker (soft delete)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["WorkshopSpeakers"],
                "summary": "Delete workshop speaker",
                "parameters": [
                    {"type": "string", "description": "the id of the workshop speaker", "name": "workshopSpeakerId", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "Success Request", "schema": {"$ref": "#/definitions/httpResponse.IdResult"}},
                    "500": {"description": "Bad Request", "schema": {"$ref": "#/definitions/errorDomain.SmartError"}}
                }
            }
        }
    },
    "definitions": {
        "domain.WorkshopSpeaker": {
            "type": "object",
            "required": ["created_by", "id", "speaker", "workshop"],
            "properties": {
                "id": {"type": "string", "example": "739bbbc9-7e93-11ee-89fd-0242ac113422"},
                "degree_abbreviation": {"type": "string", "example": "Dr."},
                "created_at": {"type": "string", "example": "2026-04-21 09:50:04"},
                "workshop": {"$ref": "#/definitions/domain.Workshop"},
                "speaker": {"$ref": "#/definitions/domain.Speaker"},
                "created_by": {"$ref": "#/definitions/domain.CreatedBy"}
            }
        },
        "domain.Workshop": {
            "type": "object",
            "required": ["id", "name"],
            "properties": {
                "id": {"type": "string", "example": "739bbbc9-7e93-11ee-89fd-0242ac113422"},
                "name": {"type": "string", "example": "TALLERES - 1ER BLOQUE"},
                "shortname": {"type": "string", "example": "1ER BLOQUE"}
            }
        },
        "domain.Speaker": {
            "type": "object",
            "required": ["document", "id", "names", "surname"],
            "properties": {
                "id": {"type": "string", "example": "739bbbc9-7e93-11ee-89fd-0242ac113422"},
                "names": {"type": "string", "example": "Alexander"},
                "surname": {"type": "string", "example": "Leon"},
                "last_name": {"type": "string", "example": "Gthub2"},
                "document": {"type": "string", "example": "73213212"}
            }
        },
        "domain.CreatedBy": {
            "type": "object",
            "required": ["id", "username"],
            "properties": {
                "id": {"type": "string", "example": "739bbbc9-7e93-11ee-89fd-0242ac113422"},
                "username": {"type": "string", "example": "admin.smart"}
            }
        },
        "domain.PaginationResults": {
            "type": "object",
            "required": ["current_page", "last_page", "size_page", "total"],
            "properties": {
                "current_page": {"type": "integer"},
                "from": {"type": "integer"},
                "last_page": {"type": "integer"},
                "size_page": {"type": "integer"},
                "to": {"type": "integer"},
                "total": {"type": "integer"}
            }
        },
        "errorDomain.SmartError": {
            "type": "object",
            "properties": {
                "code": {"type": "string"},
                "description": {"type": "string"},
                "error": {},
                "function": {"type": "string"},
                "httpStatus": {"type": "integer"},
                "layer": {"type": "string"},
                "level": {"type": "string"},
                "messages": {"type": "array", "items": {"type": "string"}},
                "raw": {"type": "string"}
            }
        },
        "httpResponse.IdResult": {
            "type": "object",
            "required": ["data", "status"],
            "properties": {
                "data": {"type": "string", "example": "201"},
                "status": {"type": "integer"}
            }
        },
        "rest.createWorkshopSpeakerValidated": {
            "type": "object",
            "required": ["speaker_id", "workshop_id"],
            "properties": {
                "workshop_id": {"type": "string", "example": "739bbbc9-7e93-11ee-89fd-0242ac113422"},
                "speaker_id": {"type": "string", "example": "739bbbc9-7e93-11ee-89fd-0242ac113422"},
                "degree_abbreviation": {"type": "string", "example": "Dr."}
            }
        },
        "rest.workshopSpeakerByIdResult": {
            "type": "object",
            "required": ["status"],
            "properties": {
                "data": {"$ref": "#/definitions/domain.WorkshopSpeaker"},
                "status": {"type": "integer"}
            }
        },
        "rest.workshopSpeakersResult": {
            "type": "object",
            "required": ["pagination", "status"],
            "properties": {
                "data": {"type": "array", "items": {"$ref": "#/definitions/domain.WorkshopSpeaker"}},
                "pagination": {"$ref": "#/definitions/domain.PaginationResults"},
                "status": {"type": "integer"}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfoworkshopSpeakers holds exported Swagger Info so clients can modify it
var SwaggerInfoworkshopSpeakers = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "workshopSpeakers",
	SwaggerTemplate:  docTemplateworkshopSpeakers,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoworkshopSpeakers.InstanceName(), SwaggerInfoworkshopSpeakers)
}
