// Code generated by mockery v2.45.0. DO NOT EDIT.

package merchants

import (
	context "context"

	domain "github.com/Benjamin-Gthub2/api-event/merchants/domain"
	mock "github.com/stretchr/testify/mock"

	paramsdomain "github.com/smart0n3/api-shared/params/domain"
)

// MerchantUseCase is an autogenerated mock type for the MerchantUseCase type
type MerchantUseCase struct {
	mock.Mock
}

// CreateMerchant provides a mock function with given fields: ctx, body
func (_m *MerchantUseCase) CreateMerchant(ctx context.Context, body domain.CreateMerchantBody) (*string, error) {
	ret := _m.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for CreateMerchant")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateMerchantBody) (*string, error)); ok {
		return rf(ctx, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateMerchantBody) *string); ok {
		r0 = rf(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateMerchantBody) error); ok {
		r1 = rf(ctx, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteMerchant provides a mock function with given fields: ctx, merchantId
func (_m *MerchantUseCase) DeleteMerchant(ctx context.Context, merchantId string) (bool, error) {
	ret := _m.Called(ctx, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMerchant")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, merchantId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnableDisableMerchant provides a mock function with given fields: ctx, merchantId, enable
func (_m *MerchantUseCase) EnableDisableMerchant(ctx context.Context, merchantId string, enable domain.EnableDisableMerchantRequest) error {
	ret := _m.Called(ctx, merchantId, enable)

	if len(ret) == 0 {
		panic("no return value specified for EnableDisableMerchant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.EnableDisableMerchantRequest) error); ok {
		r0 = rf(ctx, merchantId, enable)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMerchants provides a mock function with given fields: ctx, pagination, params
func (_m *MerchantUseCase) GetMerchants(ctx context.Context, pagination paramsdomain.PaginationParams, params domain.GetMerchantsParams) ([]domain.Merchant, *paramsdomain.PaginationResults, error) {
	ret := _m.Called(ctx, pagination, params)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchants")
	}

	var r0 []domain.Merchant
	var r1 *paramsdomain.PaginationResults
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, paramsdomain.PaginationParams, domain.GetMerchantsParams) ([]domain.Merchant, *paramsdomain.PaginationResults, error)); ok {
		return rf(ctx, pagination, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paramsdomain.PaginationParams, domain.GetMerchantsParams) []domain.Merchant); ok {
		r0 = rf(ctx, pagination, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paramsdomain.PaginationParams, domain.GetMerchantsParams) *paramsdomain.PaginationResults); ok {
		r1 = rf(ctx, pagination, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*paramsdomain.PaginationResults)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, paramsdomain.PaginationParams, domain.GetMerchantsParams) error); ok {
		r2 = rf(ctx, pagination, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetRolesByMerchant provides a mock function with given fields: ctx, merchantId
func (_m *MerchantUseCase) GetRolesByMerchant(ctx context.Context, merchantId string) ([]domain.Role, error) {
	ret := _m.Called(ctx, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for GetRolesByMerchant")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Role, error)); ok {
		return rf(ctx, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Role); ok {
		r0 = rf(ctx, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMerchant provides a mock function with given fields: ctx, merchantId, body
func (_m *MerchantUseCase) UpdateMerchant(ctx context.Context, merchantId string, body domain.UpdateMerchantBody) error {
	ret := _m.Called(ctx, merchantId, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMerchant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UpdateMerchantBody) error); ok {
		r0 = rf(ctx, merchantId, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMerchantUseCase creates a new instance of MerchantUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMerchantUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MerchantUseCase {
	mock := &MerchantUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
