// Code generated by mockery v2.45.0. DO NOT EDIT.

package merchants

import (
	context "context"

	domain "github.com/Benjamin-Gthub2/api-event/merchants/domain"
	mock "github.com/stretchr/testify/mock"

	paramsdomain "github.com/smart0n3/api-shared/params/domain"

	roles_defaultsdomain "github.com/Benjamin-Gthub2/api-event/roles-defaults/domain"
)

// MerchantRepository is an autogenerated mock type for the MerchantRepository type
type MerchantRepository struct {
	mock.Mock
}

// CreateMerchant provides a mock function with given fields: ctx, merchantId, body, defaultToMerchant
func (_m *MerchantRepository) CreateMerchant(ctx context.Context, merchantId string, body domain.CreateMerchantBody, defaultToMerchant roles_defaultsdomain.DefaultToMerchant) (*string, error) {
	ret := _m.Called(ctx, merchantId, body, defaultToMerchant)

	if len(ret) == 0 {
		panic("no return value specified for CreateMerchant")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.CreateMerchantBody, roles_defaultsdomain.DefaultToMerchant) (*string, error)); ok {
		return rf(ctx, merchantId, body, defaultToMerchant)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.CreateMerchantBody, roles_defaultsdomain.DefaultToMerchant) *string); ok {
		r0 = rf(ctx, merchantId, body, defaultToMerchant)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.CreateMerchantBody, roles_defaultsdomain.DefaultToMerchant) error); ok {
		r1 = rf(ctx, merchantId, body, defaultToMerchant)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteMerchant provides a mock function with given fields: ctx, merchantId
func (_m *MerchantRepository) DeleteMerchant(ctx context.Context, merchantId string) (bool, error) {
	ret := _m.Called(ctx, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMerchant")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, merchantId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnableDisableMerchant provides a mock function with given fields: ctx, merchantId, enable
func (_m *MerchantRepository) EnableDisableMerchant(ctx context.Context, merchantId string, enable domain.EnableDisableMerchantRequest) error {
	ret := _m.Called(ctx, merchantId, enable)

	if len(ret) == 0 {
		panic("no return value specified for EnableDisableMerchant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.EnableDisableMerchantRequest) error); ok {
		r0 = rf(ctx, merchantId, enable)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMerchants provides a mock function with given fields: ctx, pagination, params
func (_m *MerchantRepository) GetMerchants(ctx context.Context, pagination paramsdomain.PaginationParams, params domain.GetMerchantsParams) ([]domain.Merchant, error) {
	ret := _m.Called(ctx, pagination, params)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchants")
	}

	var r0 []domain.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, paramsdomain.PaginationParams, domain.GetMerchantsParams) ([]domain.Merchant, error)); ok {
		return rf(ctx, pagination, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paramsdomain.PaginationParams, domain.GetMerchantsParams) []domain.Merchant); ok {
		r0 = rf(ctx, pagination, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paramsdomain.PaginationParams, domain.GetMerchantsParams) error); ok {
		r1 = rf(ctx, pagination, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRolesByMerchant provides a mock function with given fields: ctx, merchantId
func (_m *MerchantRepository) GetRolesByMerchant(ctx context.Context, merchantId string) ([]domain.Role, error) {
	ret := _m.Called(ctx, merchantId)

	if len(ret) == 0 {
		panic("no return value specified for GetRolesByMerchant")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Role, error)); ok {
		return rf(ctx, merchantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Role); ok {
		r0 = rf(ctx, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalMerchants provides a mock function with given fields: ctx, pagination, params
func (_m *MerchantRepository) GetTotalMerchants(ctx context.Context, pagination paramsdomain.PaginationParams, params domain.GetMerchantsParams) (*int, error) {
	ret := _m.Called(ctx, pagination, params)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalMerchants")
	}

	var r0 *int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, paramsdomain.PaginationParams, domain.GetMerchantsParams) (*int, error)); ok {
		return rf(ctx, pagination, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, paramsdomain.PaginationParams, domain.GetMerchantsParams) *int); ok {
		r0 = rf(ctx, pagination, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, paramsdomain.PaginationParams, domain.GetMerchantsParams) error); ok {
		r1 = rf(ctx, pagination, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMerchant provides a mock function with given fields: ctx, merchantId, body, defaultToMerchant
func (_m *MerchantRepository) UpdateMerchant(ctx context.Context, merchantId string, body domain.UpdateMerchantBody, defaultToMerchant roles_defaultsdomain.DefaultToMerchant) error {
	ret := _m.Called(ctx, merchantId, body, defaultToMerchant)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMerchant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UpdateMerchantBody, roles_defaultsdomain.DefaultToMerchant) error); ok {
		r0 = rf(ctx, merchantId, body, defaultToMerchant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMerchantRepository creates a new instance of MerchantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMerchantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MerchantRepository {
	mock := &MerchantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
